version: '3'

services:
  neo4j:
    image: neo4j:4.4.7 #https://hub.docker.com/_/neo4j
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - neo4jdata:/data
    environment:
      NEO4J_dbms_logs_debug_level: DEBUG
      NEO4J_AUTH: none

  zookeeper:
    image: bitnami/zookeeper:3.7.1 #https://hub.docker.com/r/bitnami/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    volumes:
      - zookeeperdata:/bitnami/zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: 'yes'
  
  zoonavigator:
    image: elkozmon/zoonavigator #https://hub.docker.com/r/elkozmon/zoonavigator
    container_name: zoonavigator
    depends_on:
      - zookeeper
    ports:
      - 9000:9000
    environment:
      HTTP_PORT: 9000
      AUTO_CONNECT_CONNECTION_STRING: host.docker.internal:2181
  
  kafka:
    image: bitnami/kafka:3.0.1 #https://hub.docker.com/r/bitnami/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'yes'


volumes:
  neo4jdata:
  zookeeperdata: